// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            username = $1
    )
`

func (q *Queries) CheckUserExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (username, password_hash)
VALUES
    ($1, $2)
RETURNING
    id,
    username,
    password_hash,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserActivity = `-- name: GetUserActivity :many
BEGIN
`

type GetUserActivityRow struct {
}

func (q *Queries) GetUserActivity(ctx context.Context) ([]GetUserActivityRow, error) {
	rows, err := q.db.Query(ctx, getUserActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivityRow
	for rows.Next() {
		var i GetUserActivityRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    password_hash,
    created_at,
    updated_at
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getuserByUsername = `-- name: GetuserByUsername :one
SELECT
    id,
    username,
    password_hash,
    created_at,
    updated_at
FROM
    users
WHERE
    username = $1
`

func (q *Queries) GetuserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getuserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
