// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comments.sql

package db

import (
	"context"
	"time"

	"encore.dev/types/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO
    comments (post_id, user_id, content)
VALUES
    ($1, $2, $3)
RETURNING
    id,
    post_id,
    user_id,
    content,
    created_at,
    updated_at
`

type CreateCommentParams struct {
	PostID  uuid.UUID
	UserID  *uuid.UUID
	Content string
}

func (q *Queries) CreateComment(ctx context.Context, db DBTX, arg CreateCommentParams) (*Comment, error) {
	row := db.QueryRowContext(ctx, createComment, arg.PostID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT
    id,
    post_id,
    user_id,
    content,
    created_at,
    updated_at
FROM
    comments
WHERE
    id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, db DBTX, id uuid.UUID) (*Comment, error) {
	row := db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getLatestCommentsForPost = `-- name: GetLatestCommentsForPost :many
SELECT
    c.id,
    c.content,
    c.created_at,
    u.username AS username
FROM
    comments c
JOIN
    users u ON c.user_id = u.id
WHERE
    c.post_id = $1
ORDER BY
    c.created_at DESC
LIMIT
    $2
OFFSET
    $3
`

type GetLatestCommentsForPostParams struct {
	PostID uuid.UUID
	Limit  int32
	Offset int32
}

type GetLatestCommentsForPostRow struct {
	ID        uuid.UUID
	Content   string
	CreatedAt time.Time
	Username  string
}

func (q *Queries) GetLatestCommentsForPost(ctx context.Context, db DBTX, arg GetLatestCommentsForPostParams) ([]*GetLatestCommentsForPostRow, error) {
	rows, err := db.QueryContext(ctx, getLatestCommentsForPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetLatestCommentsForPostRow{}
	for rows.Next() {
		var i GetLatestCommentsForPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
