// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"encore.dev/types/uuid"
)

type Querier interface {
	CheckUserExists(ctx context.Context, db DBTX, username string) (bool, error)
	CreateComment(ctx context.Context, db DBTX, arg CreateCommentParams) (*Comment, error)
	CreatePost(ctx context.Context, db DBTX, arg CreatePostParams) (*Post, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (*User, error)
	GetCommentByID(ctx context.Context, db DBTX, id uuid.UUID) (*Comment, error)
	GetLatestCommentsForPost(ctx context.Context, db DBTX, arg GetLatestCommentsForPostParams) ([]*GetLatestCommentsForPostRow, error)
	GetLatestPosts(ctx context.Context, db DBTX, arg GetLatestPostsParams) ([]*GetLatestPostsRow, error)
	GetLatestUserActivity(ctx context.Context, db DBTX, arg GetLatestUserActivityParams) ([]*GetLatestUserActivityRow, error)
	GetPostByID(ctx context.Context, db DBTX, id uuid.UUID) (*Post, error)
	GetUserByID(ctx context.Context, db DBTX, id uuid.UUID) (*User, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (*User, error)
}

var _ Querier = (*Queries)(nil)
